### ISSUE TITLE
Problems in sub-windows with Golden Layout

### ISSUE THREAD

**Issue by sayefsakin** [hdc-arizona/traveler-integrated#39]
- [x] Titles keep changing for metric windows if a sub-window is dragged or re-positioned.
- [x] Multiple sub-windows on a single row changes their ordering if a different window is selected from that row.
- [x] Single clicking on the sub-window title moves the sub-window to a separate column.

**Comment by alex-r-bigelow** [comment]
I'm not sure I totally understand points 2 and 3; could you maybe add screenshots? I think some of the window management oddities might just be default GoldenLayout behavior, and some of it feels weird because we have such long window titles? Maybe we should figure out a way to shorten them (to do so, we can probably [start here](https://github.com/hdc-arizona/traveler-integrated/blob/b190fd02a9b5fe475762fd9893044040aa4628af/static/views/common/GoldenLayoutView.js#L44))? It's also possible that some of the behavior you're seeing has something to do with [how we're adding views](https://github.com/hdc-arizona/traveler-integrated/blob/b190fd02a9b5fe475762fd9893044040aa4628af/static/controller.js#L224)... there probably are smarter ways than some of that behavior.

**Comment by sayefsakin** [comment]
Thanks for solving the first one. Surprisingly, I can't reproduce the 2nd and 3rd one in my machine here in the lab. But I noticed them on may personal laptop. I guess both of them got fixed unintentionally. I'll double check with the version on my laptop and check those things out.

**Comment by sayefsakin** [comment]
fixed with the latest commit on [PR#32](https://github.com/hdc-arizona/traveler-integrated/pull/38/commits/5d69b3cb110ec04e572e072e48fdb760f1241859)
